<?php

/**
 * @file
 * Template module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_templates\Hook\WebformTemplatesHooks;

/**
 * @file
 * Provides starter templates that can be used to create new webforms.
 */

/**
 * Implements hook_entity_type_alter().
 */
#[LegacyHook]
function webform_templates_entity_type_alter(array &$entity_types) {
  \Drupal::service(WebformTemplatesHooks::class)->entityTypeAlter($entity_types);
}

/**
 * Implements hook_webform_help_info().
 */
#[LegacyHook]
function webform_templates_webform_help_info() {
  return \Drupal::service(WebformTemplatesHooks::class)->webformHelpInfo();
}
