<?php

/**
 * @file
 * Install/update/uninstall hooks.
 */

/**
 * Implements hook_uninstall().
 */
function feeds_uninstall() {
  // @todo remove keyvalue store and queue things.
}

/**
 * Resave all feed types to recalculate config dependencies.
 */
function feeds_update_8001() {
  foreach (\Drupal::entityTypeManager()->getStorage('feeds_feed_type')->loadMultiple() as $feed_type) {
    $feed_type->save();
  }
}
