<?php

/**
 * @file
 * Test module for bootstrap.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_bootstrap_test_module\Hook\WebformBootstrapTestModuleHooks1;

/**
 * @file
 * Installs and integrates the Webform Test Bootstrap theme.
 */

/**
 * Implements hook_page_attachments().
 */
#[LegacyHook]
function webform_bootstrap_test_module_page_attachments(array &$attachments) {
  \Drupal::service(WebformBootstrapTestModuleHooks1::class)->pageAttachments($attachments);
}

/**
 * Implements hook_preprocess_page().
 */
function webform_bootstrap_test_module_preprocess_page(&$variables) {
  if (!_webform_bootstrap_is_active_theme()) {
    return;
  }

  // Remove sidebar second from admin route.
  if (\Drupal::routeMatch()->getRouteObject()->getOption('_admin_route')) {
    $variables['page']['sidebar_second'] = NULL;
  }
}
