<?php

use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_query_TAG_alter() for comment_filter tag.
 * Display comments chronologically
 */
function external_comment_query_comment_filter_alter(AlterableInterface $query) {
  if ($query->getMetaData('field_name') == 'comment') {
    $order_by = &$query->getOrderBy();
    $expression = &$query->getExpressions();

    // for flat comments
    if (isset($order_by['c.cid']) && $order_by['c.cid'] == 'ASC NULLS FIRST') {
      $order_by['c.cid'] = 'DESC';
    }

    // for threaded comments
    if (isset($order_by['torder']) && $order_by['torder'] == 'ASC NULLS FIRST') {
      $expression['torder']['expression'] = 'SUBSTRING_INDEX(SUBSTRING(c.thread, 1, (LENGTH(c.thread) - 1)), \'.\', 1)';
      $order_by['torder'] = 'DESC NULLS FIRST';
      $query->addExpression('CONCAT(SUBSTRING(c.thread, 1, (LENGTH(c.thread) - 1)), \'.z\')', 'torderchild');
      $query->orderBy('torderchild', 'DESC');
    }
  }
}
