<?php

/**
 * @file
 * Contains alter_block.module.
 */

/**
 * function preprocess block for custom block for type search
 */
function alter_block_preprocess_block(&$variables)
{
  if (isset($variables['content']['#block_content']))
  {
    $content = $variables['content']['#block_content'];

    if( method_exists($content,'bundle') && $content->bundle() === 'search')
      {
        $url = $variables['content']['field_search_path'][0]['#url']->toString();
        $filterName = $variables['content']['field_search_filter'][0]['#context']['value'];

        $body = $variables['content']['body'][0]['#text'];
        $searchForm = \Drupal::formBuilder()->getForm('Drupal\gcweb\Plugin\Form\CatalogSearchBlockForm');
        $searchForm['query']['#placeholder'] = $variables['content']['field_search_placeholder'][0]['#context']['value'];
        $searchForm['url']['#value'] = $url . '&' . $filterName . '=';

        $searchFormHTML = \Drupal::service('renderer')->render($searchForm);
//        $searchFormHTML = '';
        $variables['content']['body'][0]['#text'] = $body . $searchFormHTML;
    }
  }
}
