<?php

/**
 * @file
 * Contains webform_resend.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_resend_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_resend module.
    case 'help.page.webform_resend':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Resend webform submissions') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function webform_resend_mail($key, &$message, $params) {
  switch ($key) {
   case 'testmail':
     $message['headers']['MIME-Version'] = '1.0';
     $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
     $message['headers']['From'] = 'Open Government / Gouvernement Ouvert <'. $params['from'] .'>';
     $message['headers']['Reply-to'] = 'open-ouvert@tbs-sct.gc.ca';
     $message['from'] = $params['from'];
     $message['subject'] = $params['subject'];
     $message['body'][] = $params['message'];
     break;
  }
}
