<?php

/**
 * @file
 * Test module for custom message.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_test_message_custom\Hook\WebformTestMessageCustomHooks;

/**
 * @file
 * Support module for Webform module custom message testing.
 */

/**
 * Implements hook_webform_message_custom().
 */
#[LegacyHook]
function webform_test_message_custom_webform_message_custom($operation, $id) {
  return \Drupal::service(WebformTestMessageCustomHooks::class)->webformMessageCustom($operation, $id);
}
