ckeditor5.plugin.ckeditor_codemirror_source_editing:
  type: config_object
  label: 'CodeMirror Code Editor settings'
  mapping:
    enable:
      type: boolean
      label: 'Enabled'
    mode:
      type: string
      label: 'Mode'
    options:
      type: config_object
      label: 'CodeMirror options'
      mapping:
        autoCloseBrackets:
          type: boolean
          label: 'Close brackets automatically.'
        autoCloseTags:
          type: boolean
          label: 'Close tags automatically.'
        folding:
          type: boolean
          label: 'Enable code folding.'
        lineNumbers:
          type: boolean
          label: 'Show line numbers.'
        lineWrapping:
          type: boolean
          label: 'Enable line wrapping.'
        matchBrackets:
          type: boolean
          label: 'Highlight matching brackets.'
        matchTags:
          type: boolean
          label: 'Highlight matching tags.'
        searchBottom:
          type: boolean
          label: 'Display search bar at bottom.'
        styleActiveLine:
          type: boolean
          label: 'Highlight active line.'
