<?php

/**
 * @file
 * Provides the webform ui.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_ui\Hook\WebformUiHooks;

/**
 * @file
 * Provides a simple user interface for building and maintaining webforms.
 */

/**
 * Implements hook_entity_type_alter().
 */
#[LegacyHook]
function webform_ui_entity_type_alter(array &$entity_types) {
  if (\Drupal::hasService(WebformUiHooks::class)) {
    \Drupal::service(WebformUiHooks::class)->entityTypeAlter($entity_types);
  }
}

/**
 * Implements hook_preprocess_menu_local_action().
 *
 * Add .button--secondary to add page and layout actions.
 *
 * @see Drupal.behaviors.webformUiElementsActionsSecondary
 */
function webform_ui_preprocess_menu_local_action(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() !== 'entity.webform.edit_form') {
    return;
  }

  if (in_array($variables['link']['#url']->getRouteName(), ['entity.webform_ui.element.add_page', 'entity.webform_ui.element.add_layout'])) {
    $variables['link']['#options']['attributes']['class'][] = 'button--secondary';
  }
}
