<?php

/**
 * @file
 * Main code for CKEditor CodeMirror module.
 */

/**
 * Gets the path of a library.
 *
 * @return bool|string
 *   The path to the specified library or FALSE if the library wasn't found.
 */
function _ckeditor_codemirror_get_library_path(string $library): bool|string {
  $path = "libraries/$library";
  if (file_exists($path)) {
    return DRUPAL_ROOT . "/$path";
  }
  return FALSE;
}

/**
 * Gets the version information for a library.
 *
 * @return string
 *   A string containing the version of the library or empty if the version
 *   cannot be found.
 */
function _ckeditor_codemirror_get_library_version(string $library): string {
  $library_path = _ckeditor_codemirror_get_library_path($library);
  $data = json_decode(file_get_contents("$library_path/package.json"));
  return $data?->version ?? '';
}
