<?php

/**
 * @file
 * Test module for webform options.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_test_options\Hook\WebformTestOptionsHooks;

/**
 * @file
 * Support module for webform that provides form alter hook for wizard cause tests.
 */

/**
 * Implements hook_webform_options_WEBFORM_OPTIONS_ID_alter() for webform options test.
 */
function webform_test_options_webform_options_test_alter(array &$options, array &$element) {
  $options += [
    'four' => t('Four'),
    'five' => t('Five'),
    'six' => t('Six'),
  ];
}

/**
 * Implements hook_webform_options_alter().
 */
#[LegacyHook]
function webform_test_options_webform_options_alter(array &$options, array &$element, $id) {
  \Drupal::service(WebformTestOptionsHooks::class)->webformOptionsAlter($options, $element, $id);
}
