display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
          reset_button_label: Effacer
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      fields:
        date_published:
          label: 'Date de publication '
        date_released:
          label: 'Date de diffusion'
        nothing:
          label: Votez
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
      empty:
        area_text_custom:
          content: "<p><strong>Aucun résultat trouvé.</strong></p> \r\n<p>Veuillez entrer un nouveau mot-clé.</p>\r\n<br/><br/>\r\n"
