label: Commentaires
description: 'Trouver et gérer les commentaires.'
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: "‹\_précédent"
            next: "suivant\_›"
            first: "«\_premier"
            last: "dernier\_»"
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        comment_bulk_form:
          action_title: Action
        subject:
          label: Subject
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        entity_id:
          label: 'Posted in'
          separator: ', '
        created:
          label: 'Post date'
          separator: ', '
        operations:
          label: Actions
        name_1:
          separator: ', '
      filters:
        subject:
          expose:
            label: Subject
        combine:
          expose:
            label: 'Nom de l''auteur'
      title: Commentaires
      empty:
        area_text_custom:
          content: 'Aucun commentaire disponible.'
      use_more_text: plus
  page_published:
    display_title: 'Commentaires publiés'
    display_options:
      menu:
        title: Commentaires
        description: 'Commentaires publiés'
      display_description: 'La liste des commentaires approuvés.'
      fields:
        comment_bulk_form:
          action_title: Action
        subject:
          label: Subject
          separator: ', '
        comment_body:
          label: Commentaire
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        entity_id:
          label: 'Posted in'
          separator: ', '
        created:
          label: 'Post date'
          separator: ', '
        operations:
          label: Actions
        name_1:
          separator: ', '
  page_unapproved:
    display_title: 'Commentaires non aprouvés'
    display_options:
      menu:
        title: 'Commentaires non aprouvés'
        description: 'Commentaires non-approuvés'
      display_description: 'The unapproved comments listing.'
      filters:
        subject:
          expose:
            label: Subject
        combine:
          expose:
            label: 'Nom de l''auteur'
      fields:
        comment_bulk_form:
          action_title: Action
        subject:
          label: Subject
          separator: ', '
        comment_body:
          label: Commentaire
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        entity_id:
          label: 'Posted in'
          separator: ', '
        created:
          label: 'Post date'
          separator: ', '
        operations:
          label: Actions
        name_1:
          separator: ', '
  rest_export_1:
    display_title: 'REST export'
    display_options:
      display_description: 'The unapproved comments listing.'
      fields:
        type:
          label: Type
          separator: ', '
        entity_id:
          label: 'Posted in'
          separator: ', '
        view_node:
          label: Link
          text: view
        field_url:
          separator: ', '
        created:
          label: 'Posted on'
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        subject:
          label: Subject
          separator: ', '
        comment_body:
          label: Commentaire
          separator: ', '
