display:
  default:
    display_options:
      fields:
        ref_number:
          label: 'Numéro de demande'
        date_year:
          label: Année
        pos_number:
          label: 'Numéro du poste'
        old_class_level:
          label: 'Numéro de niveau de la classification du poste reclassifié'
      title: 'Reclassification de poste du gouvernement'
      footer:
        area_text_custom:
          content: '<p class="mrgn-tp-lg mrgn-bttm-xl"><a class="btn btn-primary" href="/fr/search/reclassification">Retour à la recherche&nbsp;<span class="fa fa-undo"></span></a></p>'
