display:
  default:
    display_options:
      fields:
        ref_number:
          label: 'Numéro de demande'
        file_id_number:
          label: 'Numéro d’identification du fichier'
        date_clean:
          label: 'Date d’identification du fichier'
      title: 'Actes répréhensibles fondés'
      footer:
        area_text_custom:
          content: "<p class=\"mrgn-tp-lg mrgn-bttm-xl\"><a class=\"btn btn-primary\" href=\"/fr/search/wrongdoing\">Retour à la recherche&nbsp;<span class=\"fa fa-undo\"></span></a></p>\r\n"
