label: 'Contenu récent'
description: 'Contenu récent.'
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          label: Title
          separator: ', '
        type:
          label: 'Content type'
          separator: ', '
        changed:
          label: Changed
          separator: ', '
        moderation_state:
          label: Status
          separator: ', '
      title: 'Contenu récent'
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
      use_more_text: Plus
  block_1:
    display_title: Bloc
