display:
  default:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n<div class=\"col-sm-8\">\r\n<h2 class=\"h4 mrgn-tp-0\"><a href=\"/fr/search/wrongdoing/reference/{{ id }}\"><span class=\"hgl\">{{ findings_conclusions_fr }}</span></a></h2>\r\n<p><small><strong>Organisation:</strong> <span class=\"hgl\">{{ org_name_fr}}</span><br />Numéro de demande : <span class=\"hgl\">{{ ref_number }}</span></small></p>\r\n</div>\r\n<div class=\"col-sm-4 text-right\">\r\n<span class=\"h3 mrgn-tp-0\"><span class=\"hgl\">{{ file_id_number }}</span></small></sup></span><br />\r\n<small>{{ date_clean }}</small>\r\n</div>\r\n</div>"
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
          reset_button_label: Effacer
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      filters:
        search_api_fulltext:
          expose:
            label: Recherche
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
      empty:
        area_text_custom:
          content: "<p><strong>Aucun résultat trouvé.</strong></p> \r\n<p>Veuillez entrer un nouveau mot-clé.</p>\r\n<br/><br/>\r\n"
