display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        status:
          label: Status
      filters:
        environment:
          group_info:
            group_items:
              1:
                title: Serveur
              8:
                title: Développement
        status:
          expose:
            label: statut
          group_info:
            label: Status
      header:
        result:
          content: 'Displaying @start - @end of @total'
      empty:
        area_text_custom:
          content: "Aucun résultat n'a été trouvé."
  page_1:
    display_options:
      fields:
        status:
          label: Status
      filters:
        environment:
          group_info:
            group_items:
              1:
                title: Serveur
              8:
                title: Développement
        status:
          expose:
            label: statut
          group_info:
            label: Status
  page_2:
    display_options:
      arguments:
        id:
          exception:
            title: Tout
