display:
  default:
    display_options:
      fields:
        ref_number:
          label: 'Numéro de demande'
        recipient_business_number:
          label: 'Numéro de l’entreprise bénéficiaire'
        recipient_legal_name:
          label: 'Nom légal du bénéficiaire'
        recipient_city:
          label: Ville
        recipient_postal_code:
          label: 'Code postal du bénéficiaire'
        federal_riding_number:
          label: 'Numéro de la circonscription fédérale'
        naics_identifier:
          label: 'Identificateur du SCIAN'
        agreement_number:
          label: 'Numéro de l’entente'
        agreement_value:
          label: 'Valeur de l’entente en dollars canadiens'
        agreement_start_date:
          label: 'Date de début de l’entente'
        coverage:
          label: Portée
        agreement_end_date:
          alter:
            text: '{{ agreement_end_date|trim|date(''Y-m-d'') }}'
        amendment_date:
          label: 'Date de modification'
      title: 'Subventions et des contributions gouvernementaux'
      footer:
        area_text_custom:
          content: "<p class=\"mrgn-tp-lg mrgn-bttm-xl\"><a class=\"btn btn-primary\" href=\"/fr/search/grants\">Retour à la recherche&nbsp;<span class=\"fa fa-undo\"></span></a></p>\r\n"
