label: Fichiers
description: 'Trouver et gérer les fichiers.'
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        fid:
          label: 'Identifiant (FID)'
        filename:
          label: Nom
          separator: ', '
        filemime:
          label: 'Type MIME'
        filesize:
          label: Taille
        status:
          label: Status
          settings:
            format_custom_false: Temporaire
            format_custom_true: Permanent
        created:
          label: 'Date de transfert'
        changed:
          label: 'Date de modification'
        count:
          label: 'Utilisé dans'
      filters:
        filename:
          expose:
            label: 'Nom du fichier'
        filemime:
          expose:
            label: 'Type MIME'
        status:
          expose:
            label: Status
      title: Fichiers
      empty:
        area_text_custom:
          content: 'Aucun fichier disponible.'
  page_1:
    display_title: 'Vue d''ensemble des fichiers'
    display_options:
      menu:
        title: Fichiers
  page_2:
    display_title: 'Utilisation du fichier'
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        entity_label:
          label: Entité
        type:
          label: 'Type d''entité'
        module:
          label: 'Enregistrement du module'
        count:
          label: 'Nombre d''utilisations'
      title: 'Utilisation du fichier'
      arguments:
        fid:
          exception:
            title: Tout
          title: 'Information d''utilisation du fichier {{ arguments.fid }}'
