label: 'Commentaires récents'
description: 'Commentaires récents.'
display:
  default:
    display_title: Maître
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        name:
          separator: ', '
        created:
          separator: ', '
        comment_body:
          separator: ', '
        title:
          separator: ', '
      title: 'Commentaires récents'
      empty:
        area_text_custom:
          content: 'Aucun commentaire disponible.'
  block_1:
    display_title: Bloc
    display_options:
      block_description: 'Commentaires récents'
      block_category: 'Listes (Views)'
      fields:
        subject:
          label: Title
          separator: ', '
        name:
          separator: ', '
        created:
          label: Date
          separator: ', '
  block_2:
    display_options:
      fields:
        name:
          separator: ', '
        created:
          separator: ', '
        comment_body:
          separator: ', '
        title:
          separator: ', '
