elements: |
  entity_id:
    '#title': 'Indentificateur unique'
  organization:
    '#title': Organisation
  org_name:
    '#title': Organisation
  year:
    '#title': Année
  month:
    '#title': Mois
  request_number:
    '#title': 'Numéro de la demande'
  summary:
    '#title': 'Résumé de la demande'
  number_of_pages:
    '#title': 'Nombre de pages'
  pages:
    '#title': 'Nombre de pages'
  e_mail_ati_recipient:
    '#title': Courriel
  ati_email:
    '#title': Courriel
  requestor_category:
    '#title': 'Catégorie de demandeur'
    '#description': 'Sélectionnez la catégorie qui vous décrit le mieux.'
    '#options':
      1: 'Secteur universitaire'
      2: 'Secteur commercial (secteur privé)'
      3: Médias
      4: Organisation
      5: 'Membre du public'
      6: 'Je refuse de m''identifier'
  delivery_method:
    '#title': 'Mode de livraison'
    '#description': '<strong>S''il vous plaît noter</strong> L''institution devra retourner, dans la mesure du possible, les documents demandés dans le format choisi. Toutefois, il sera parfois impossible de le faire dû aux contraintes de la taille des documents électroniques.'
    '#options':
      1: 'copie électronique'
      2: 'examen en personne'
      3: 'copier papier'
  given_name:
    '#title': Prénom
  family_name:
    '#title': 'Nom de famille'
  your_e_mail_address:
    '#title': 'Votre adresse de courriel'
  your_telephone_number:
    '#title': 'Votre numéro de téléphone'
  additional_comments:
    '#title': 'Commentaires supplémentaires'
    '#description': 'Expliquez la nature de votre requête ou la raison pour laquellle contactez cette organisation.'
  address_fieldset:
    '#title': Addresse
  preferred_language_of_correspondence:
    '#title': 'Langue de préférence pour communiquer avec vous'
  please_note:
    '#markup': '<strong>S''il vous plaît noter:</strong>&nbsp;Institutions travailleront pour répondre à votre demande pour ce paquet précédemment publiée dès que possible.'
  consent:
    '#title': 'Je déclare avoir lu et compris l''énoncé de confidentialité ci-dessus et je l''accepte.'
  actions:
    '#title': 'Bouton(s) de soumission'
title: 'Demande informelle d''enregistrements AI précédemment publiés'
description: '&quot;Informal Request for AI Records Previously Released&quot; webform.'
settings:
  confirmation_title: 'Demande informelle d''enregistrements AI précédemment publiés'
  confirmation_message: 'Votre demande informelle d''enregistrements AI précédemment publiés a été soumise.'
handlers:
  confirmation:
    label: Confirmation
    settings:
      from_name: _default
      body: "<p>Ceci est un courriel automatisé. Vous le recevez parce que vous avez communiqué avec une organisation au sujet d’une demande d’accès à l’information. Voici les valeurs que vous avez soumises :</p>\r\n\r\n<p><strong>Soumis le :</strong> [webform_submission:created]</p>\r\n<p><strong>Proposé par :</strong> [webform_submission:user]</p>\r\n<p>Les valeurs soumises sont : </p>\r\n[webform_submission:values]\r\n"
  notifications:
    settings:
      from_name: _default
      body: "Ceci est un courriel automatisé. Vous le recevez parce que vous avez communiqué avec une organisation au sujet d’une demande d’accès à l’information. Voici les valeurs que vous avez soumises :\r\n\r\nSoumis le : [webform_submission:created]\r\nProposé par : [webform_submission:user]\r\nLes valeurs soumises sont :\r\n[webform_submission:values]\r\n"
