title: 'Proposez une idée pour le Consultation Plan d''action'
elements: |
  add_your_idea:
    '#title': 'Ajoutez votre idée'
    '#description': 'Pour ajouter votre idée, indiquez votre nom, le thème de votre idée et une description de celle ci dans les champs ci dessous.'
  your_name_optional:
    '#title': 'Votre nom (facultatif)'
  your_idea_label:
    '#markup': '<p>Décrivez votre idée. Assurez vous de mentionner tous les jalons ou les principaux produits livrables qui pourraient être concrétisés au cours des deux premières années. Vous voudrez sans doute mentionner aussi les partenaires potentiels qui pourraient contribuer à la mise en œuvre de votre idée.</p>'
  title:
    '#title': Titre
  your_idea:
    '#title': 'Votre idée'
handlers:
  email:
    label: Courriel
    settings:
      from_name: _default
      subject: 'Proposez une idée pour le plan d''action sur la transparence gouvernementale'
      body: "&lt;p&gt;Soumis le [webform_submission:created]&lt;/p&gt;<br />\r\n&lt;p&gt;Soumis par : [webform_submission:user]&lt;/p&gt;<br />\r\n&lt;p&gt;Les valeurs soumises sont :&lt;/p&gt;<br />\r\n[webform_submission:values]<br />\r\n<br />\r\nLes résultats de cette soumission peuvent être vus ici :<br />\r\n[webform_submission:url]\r\n"
