elements: |
  given_name:
    '#title': Prénom
  family_name:
    '#title': 'Nom de famille'
  your_e_mail_address:
    '#title': 'Votre adresse de courriel'
  additional_comments:
    '#title': 'Commentaires supplémentaires'
  org_name_en:
    '#title': Organisation
  ref_number:
    '#title': 'Numéro de référence'
  markup:
    '#markup': "<br />Veuillez noter que les institutions répondront à votre demande à l’intérieur des  5 jours ouvrables. Si votre demande est soumise en dehors des heures d'ouverture, le prochain jour ouvrable commencera le compte à rebours afin de répondre à votre demande.\n"
  i_have_read_understood_and_agree_with_the_above_privacy_notice_:
    '#title': 'Je déclare avoir lu et compris l''énoncé de confidentialité et l’avertissement ci-dessus et je l''accepte'
    '#options':
      'Yes': Oui
