elements: |
  title_of_the_event:
    '#title': 'Titre d’evénement'
  link_to_information_or_registration_page:
    '#title': 'Lien vers l’information ou la page d’inscription'
  host_organization:
    '#title': 'Organisation d’accueil'
  your_email_address:
    '#title': 'Adresse courriel'
  location_city_and_province_or_territory_or_online_:
    '#title': 'Lieu (ville et province ou territoire)'
  time:
    '#title': 'Heure (Optionnel)'
settings:
  confirmation_message: 'Merci d&rsquo;avoir inscrit votre &eacute;v&eacute;nement pour la Semaine du gouvernement ouvert. Nous l&rsquo;ajouterons &agrave; notre site web et avons h&acirc;te d&rsquo;en entendre parler! Entre-temps, assurez-vous de consulter <a href="https://open.canada.ca/en/content/open-government-week#toc3">nos ressources</a>, incluant la <a href="https://ouvert.canada.ca/fr/contenu/semaine-du-gouvernement-ouvert-trousse-doutils-promotionnels">trousse d&rsquo;outils pour organiser votre &eacute;v&eacute;nement</a>. Vous pouvez &eacute;galement <a href="mailto:OGweek-SemaineGO@tbs-sct.gc.ca">nous contacter</a> si vous avez des questions.'
