title: 'Proposez un jeu de données'
description: 'DEPRECATED - &quot;Suggest a Dataset&quot; webform.'
elements: |
  name_of_dataset:
    '#title': 'Nom du jeu de données'
  federal_government_institution:
    '#title': 'Institution du gouvernement fédérale qui publie le jeu de données'
  description_dataset:
    '#title': 'Description du jeu de données que vous aimeriez rendre public'
  additional_comments_and_feedback:
    '#title': 'Rétroaction et commentaires supplémentaires'
  first_name:
    '#title': Prénom
  last_name:
    '#title': 'Nom de famille'
  title:
    '#title': Titre
  organization:
    '#title': Organisation
  e_mail_address:
    '#title': 'Adresse électronique'
  telephone:
    '#title': Téléphone
  consent:
    '#title': Consens
    '#description': 'Je consens à la communication de mes renseignements personnels entre les ministères du gouvernement du Canada dans le but de répondre à ma demande de renseignements.'
  actions:
    '#title': 'Bouton(s) de soumission'
settings:
  confirmation_message: 'Merci pour votre soumission. Votre demande sera traitée et ajoutée à la page « Proposez un jeu de données » dès que possible.'
handlers:
  email:
    label: Courriel
    settings:
      from_name: _default
      body: "Soumis le [webform_submission:created]<br />\r\nSoumis par : [webform_submission:user]<br />\r\nLes valeurs soumises sont :<br />\r\n[webform_submission:values]<br />\r\n<br />\r\nLes résultats de cette soumission peuvent être vus ici :<br />\r\n[webform_submission:url]\r\n"
