elements: |
  rating:
    '#title': 'Avez-vous trouvé ce jeu de données utile?'
  actions:
    '#submit__label': Évaluez
settings:
  previous_submission_message: 'Vous avez d&eacute;j&agrave; vot&eacute; sur ce jeu de donn&eacute;es'
  previous_submissions_message: 'Vous avez d&eacute;j&agrave; vot&eacute; sur ce jeu de donn&eacute;es'
  confirmation_message: 'Merci d&#39;avoir vot&eacute; sur ce jeu de donn&eacute;es.'
