elements: |
  rating:
    '#title': 'Avez-vous trouvé cet applis utile?'
  actions:
    '#submit__label': Coter
settings:
  previous_submission_message: 'Vous avez déjà voté sur cet applis'
  previous_submissions_message: 'Vous avez déjà voté sur cet applis'
  confirmation_message: "Merci d'avoir voté sur cet applis."
