title: 'Proposez un jeu de données'
elements: |
  page_1:
    '#title': Proposition
  title_of_dataset:
    '#title': 'Titre du jeu de données'
    '#description': '<p class="text-info">Ce champ indique le titre en anglais du jeu de données proposé. Exemplar : Comportement du vent au Canada 2016 - 2019</p>'
  department:
    '#title': 'L’institution gouvernementale qui publie un jeu de données'
    '#description': '<p class="text-info">Ce champ décrit l’institution gouvernementale qui publie le jeu de données proposé. Si vous souhaitez obtenir des données provinciales, veuillez vous adresser à la <a href="[site:url]/cartes/donnees-ouvertes-au-canada#toc1">province ou au territoire</a> concerné. Veuillez sélectionner <strong>«Autre»</strong> si vous ne connaissez pas le nom de l’organisation. Exemplar : Environnement et Changement climatique Canada</p>'
    '#other__option_label': Autre
    '#other__placeholder': 'Veuillez préciser'
  description_dataset:
    '#title': 'Description du jeu de données que vous aimeriez qui soit rendu disponible'
    '#description': '<p class="text-info">Ce champ contient une description du jeu de données proposé. Exemplar : Ce jeu de données devrait contenir des données ayant été recueillies au fil des années 2016-2019, et ayant trait aux configurations des vents canadiens, d’un océan à l’autre.</p>'
  additional_comments_and_feedback:
    '#title': 'Rétroaction et commentaires supplémentaires'
    '#description': '<p class="text-info">Exemplar : Ces données étaient disponible pour les années 2010-2015 mais n’ont pas été publiées depuis.</p>'
  dataset_subject:
    '#title': 'Proposez des domaines pour ce jeu de données'
    '#description': '<p class="text-info">Pour sélectionner plusieurs éléments, cliquez sur chacun d’eux tout en maintenant la touche Ctrl enfoncée. Exemplar : Nature et environnement, Sciences et technologie</p>'
  dataset_keywords:
    '#title': 'Catégorisez votre jeu de données par des mots descriptifs séparés par des virgules'
    '#description': '<p class="text-info">Exemplar : La météo, l’environnement et le Changement climatique Canada, la configuration des vents</p>'
  reason:
    '#title': 'Raison de la demande d’un jeu de données'
    '#description': '<p class="text-info">Exemplar : Pédagogique</p>'
  personal_information_optional_:
    '#title': 'Renseignements sur les personnes-ressources'
    '#prev_button_label': '< Précédent'
  first_name:
    '#title': Prénom
  last_name:
    '#title': 'Nom de famille'
  title:
    '#title': Titre
  organization:
    '#title': Organisation
  e_mail_address:
    '#title': 'Adresse électronique'
    '#description': '<p class="text-info">Exemplar : user@email.com</p>'
  telephone:
    '#title': Téléphone
  user_consent:
    '#title': 'Je consens à ce que mes renseignements personnels soient transmis d’un ministère du gouvernement du Canada à l’autre dans le but de répondre à ma demande.'
  actions:
    '#title': 'Bouton(s) de soumission'
settings:
  confirmation_message: 'Merci pour votre soumission. Votre demande sera traitée et ajoutée à la page « Proposez un jeu de données » dès que possible.'
  preview_message: 'Veuillez réviser votre soumission. Elle ne sera pas complète tant que vous n’aurez pas appuyé sur le bouton « Soumettre »!'
handlers:
  email:
    label: Courriel
    settings:
      from_name: default
      body: "Soumis le [webform_submission:created]<br />\r\nSoumis par : [webform_submission:user]<br />\r\nLes valeurs soumises sont :<br />\r\n[webform_submission:values]<br />\r\n<br />\r\nLes résultats de cette soumission peuvent être vus ici :<br />\r\n[webform_submission:url]\r\n"
  email_1:
    settings:
      body: "<p>Merci pour votre soumission. Votre demande sera traitée et ajoutée à la page « Proposez un jeu de données » dès que possible.</p>\r\n[webform_submission:values]"
description: 'Formulaire de proposition d’un jeu de données '
