elements: |
  page_1:
    '#title': 'Ajouter des métadonnées au jeu de données'
  title:
    '#title': Titre
    '#description': '<p class="text-info">Nom français désignant le jeu de données. Exemplar : University Student Dropout Rate</p>'
  creator:
    '#title': Auteur
    '#description': '<p class="text-info">Entités individuelles (personnes) principalement responsables de produire le jeu de données (séparer les multiples entités par des virgules). Exemplar : John Smith</p>'
  contact_email:
    '#title': 'Courriel - Personne-ressource'
    '#description': '<p class="text-info">Courriel de la personne-ressource à contacter au sujet du jeu de données ou de l’ensemble de données. Exemplar : example@email.com</p>'
  description:
    '#description': '<p class="text-info">Description de la ressource d’information, en français. La description peut comprendre un résumé, une table des matières ou un texte libre. Exemplar : Taux annuel d’abandon des étudiants pour les universités contenant les informations démographiques suivantes ….</p>'
  keywords:
    '#title': 'Mots clés'
    '#description': '<p class="text-info">Mots ou phrases couramment utilisés qui décrivent le jeu de données, en anglais. (Séparer les mots ou phrases par une virgule).</p>'
  subject:
    '#title': Sujet
    '#description': '<p class="text-info">Le sujet du contenu du jeu de données. Vous pouvez sélectionner ou désélectionner de multiples sujets (Ctrl+Clic)</p>'
  maintenance_and_update_frequency:
    '#title': 'Fréquence d’entretien et de mise à jour'
    '#description': '<p class="text-info">Fréquence à laquelle les changements et les ajouts sont apportés au jeu de données initial</p>'
  date_published:
    '#title': 'Date de publication'
    '#description': '<p class="text-info">Date de publication du jeu de données (AAAA-MM-JJ)</p>'
  page_2:
    '#title': 'Métadonnées additionnelles pour le jeu de données'
  audience:
    '#description': '<p class="text-info">Description de l’audience ou du groupe de personnes pour lequel le jeu de données décrit est destiné ou utile. Vous pouvez sélectionner ou désélectionner de multiples options (Ctrl+Clic)</p>'
  time_period_coverage_start:
    '#title': 'Couverture de la période de temps - date de début'
    '#description': '<p class="text-info">Date de début de la période couverte par le jeu de données (AAAA-MM-JJ)</p>'
  time_period_coverage_end:
    '#title': 'Couverture de la période de temps - date de fin'
    '#description': '<p class="text-info">Date de fin de la période couverte par le jeu de données (AAAA-MM-JJ)</p>'
  date_modified:
    '#title': 'Date de modification'
    '#description': '<p class="text-info">Date à laquelle le jeu de données a été mis à jour (AAAA-MM-JJ)</p>'
  homepage_url:
    '#title': 'URL de la page d’accueil'
    '#description': '<p class="text-info">Programme ou page d’accueil pouvant être consulté pour obtenir de l’information supplémentaire ou contextuelle au sujet du jeu de données, en français</p>'
  digital_object_identifier:
    '#title': 'Identificateur d’objet numérique'
    '#description': '<p class="text-info mrgn-bttm-lg">L’identificateur d’objet numérique assigné au jeu de données. Pour obtenir de plus amples renseignements, veuillez consulter le site <a href="http://cisti-icist.nrc-cnrc.gc.ca/fra/services/icist/datacite-canada/index.html">http://cisti-icist.nrc-cnrc.gc.ca/fra/services/icist/datacite-canada/index.html</a>.</p>'
  page_3:
    '#title': 'Ajouter une ressource'
  resource_title:
    '#title': 'Titre de la ressource'
    '#description': '<p class="text-info">Nom français attribué à la ressource</p>'
  language:
    '#title': Langue
    '#description': '<p class="text-info">Langue de la ressource. Vous pouvez sélectionner ou désélectionner de multiples langues (Ctrl+Clic)</p>'
  download_url:
    '#title': 'Télécharger un URL'
    '#description': '<p class="text-info">Emplacement pour l’accès en ligne aux fins de la distribution de la ressource</p>'
  unique_identifier:
    '#title': 'Identificateur unique'
    '#description': '<p class="text-info">Expression ou chaîne unique désignant la ressource</p>'
  resource_date_published:
    '#title': 'Date de publication'
    '#description': '<p class="text-info">Date officielle d’émission (c.-à-d. de publication) de la ressource</p>'
  resource_type:
    '#title': 'Type de content'
    '#description': '<p class="text-info">Nature ou genre du contenu de la ressource</p>'
  size:
    '#title': Taille
    '#description': '<p class="text-info">Taille [estimative] d’une distribution en octets</p>'
  character_set:
    '#title': 'Jeu de caractères'
    '#description': '<p class="text-info">Nom complet de la norme de codage des caractères utilisée pour le ressource</p>'
  format:
    '#description': '<p class="text-info">Format du fichier, support physique ou dimensions de la ressource</p>'
  licence:
    '#description': '<p class="text-info">Licence s’appliquant au jeu de données</p>'
title: 'Contenu auquel les utilisateurs ont contribué'
handlers:
  email:
    settings:
      subject: '[webform:title]'
      body: "<p>Nous avons reçu votre soumission pour le Portail du gouvernement ouvert. Merci de votre contribution. Nous examinons présentement votre soumission. </p>\r\n\r\n<p>Présenté le [webform_submission:created]</p>\r\n\r\n<p>Les valeurs soumises sont\_:</p>\r\n[webform_submission:values]"
settings:
  confirmation_message: "<p>Nous vous remercions d’avoir contribué au Portail du gouvernement ouvert. Nous examinons présentement votre soumission.</p>\r\n\r\n<p>Parcourir la collection de plus de 80 000 <a href=\"https://rechercher.ouvert.canada.ca/fr/od/\">ressources d’information et de données ouvertes</a>.</p>"
