title: 'Soumettre votre application'
elements: |
  title:
    '#title': Titre
    '#description': 'Nom sous lequel l’application mentionnée est connue.'
  abstract:
    '#title': Résumé
    '#description': 'Résumé narratif succinct de l’application. Veuillez envoyer des captures décran de l’application par courriel à <a href="mailto:open-ouvert@tbs-sct.gc.ca">open-ouvert@tbs-sct.gc.ca</a>'
  subject:
    '#title': Sujet
    '#description': 'Principal sujet (principaux sujets) de l’application.'
    '#options':
      Arts_Music_Literature: 'Arts, musique, littérature'
      Economics_and_Industry: 'Économie et de l''Industrie'
      Education_and_Training: 'Éducation et formation'
      Government_and_Politics: 'Gouvernement et politique'
      Health_and_Safety: 'Santé et sécurité'
      History_and_Archaeology: 'Histoire et archéologie'
      Information_and_Communications: 'Information et des communications'
      Labour: Travail
      Language_and_Linguistics: 'Langue et linguistique'
      Law: Droit
      Military: Militaire
      Nature_and_Environment: 'Nature et environnement'
      Persons: Personnes
      Processes: Processus
      Science_and_Technology: 'Science et technologie'
      Society_and_Culture: 'Société et culture'
  keywords:
    '#title': Mots-clés
    '#description': 'Mot(s) fréquemment utilisé(s) ou mot(s) ou phrase(s) formalisé(s) employé(s) pour décrire l’objet de l’application. (p. ex. Air, Qualité de l’air, Polluants organiques)'
  date_published:
    '#title': 'Date de publication'
    '#description': 'Date à laquelle l’application a été publiée.'
  date_modified:
    '#title': 'Date de modification'
    '#description': 'Date à laquelle l’application a été mise à jour ou modifiée.'
  language:
    '#title': Langue
    '#description': 'Langue de l’application.'
    '#options':
      English: Anglais
      French: Français
  access_url:
    '#title': 'URL d’accès'
    '#description': 'Emplacement électronique où l’on peut trouver l’application.'
  datasets_used:
    '#title': 'Jeux de données utilisés'
    '#description': 'Nom du jeue de données utilisé pour créer l’application.'
  organization_name:
    '#title': 'Nom de l’organisation'
  application_type:
    '#title': 'Type d’application'
    '#description': 'Type d’application.'
    '#options':
      web_based: 'Basé sur le Web'
  format:
    '#description': 'Format de l’application.'
    '#options':
      web_based: 'Basé sur le Web'
  homepage_screenshot:
    '#title': 'Saisie d’écran de la page d’accueil'
    '#description': 'Saisie d’écran de la page d’accueil de l’application (Max. 2 Mo)'
  results_page_screenshot:
    '#title': 'Saisie d’écran de la page des résultats'
    '#description': 'Saisie d’écran de la page des résultats ou autre couche de l’application (Max. 2 Mo)'
  contact_information:
    '#markup': '<h2>Coordonnées</h2>'
  first_name:
    '#title': Prénom
  last_name:
    '#title': 'Nom de famille'
  contact_title:
    '#title': Titre
  organization:
    '#title': Organisation
  e_mail_address:
    '#title': 'Adresse électronique'
  telephone:
    '#title': Téléphone
  consent:
    '#title': Consens
    '#description': 'Je consens à l’échange de l’information fournie dans le présent formulaire, y compris mes renseignements personnels, entre les ministères du gouvernement du Canada, afin de faciliter la compréhension de l’utilisation des jeux de données du gouvernement du Canada et l’élaboration des initiatives de données ouvertes du gouvernement du Canada.'
  actions:
    '#title': 'Bouton(s) de soumission'
settings:
  confirmation_message: 'Merci pour votre soumission. Votre demande sera traitée et ajoutée à la galerie d’applis dès que possible.'
handlers:
  email:
    label: Courriel
    settings:
      from_name: _default
      subject: 'Soumettre votre application'
      body: "Soumis le [webform_submission:created]<br />\r\nSoumis par : [webform_submission:user]<br />\r\nLes valeurs soumises sont :<br />\r\n[webform_submission:values]<br />\r\n<br />\r\nLes résultats de cette soumission peuvent être vus ici :<br />\r\n[webform_submission:url]\r\n"
