<?php

/**
 * @file
 * Test module for input masks.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_test_element_input_masks\Hook\WebformTestElementInputMasksHooks;

/**
 * @file
 * Support module for webform that provides element plugin tests.
 */

/**
 * Implements hook_webform_element_input_masks().
 */
#[LegacyHook]
function webform_test_element_input_masks_webform_element_input_masks() {
  return \Drupal::service(WebformTestElementInputMasksHooks::class)->webformElementInputMasks();
}

/**
 * Implements hook_webform_element_input_masks_alter().
 */
#[LegacyHook]
function webform_test_element_input_masks_webform_element_input_masks_alter(array &$input_masks) {
  \Drupal::service(WebformTestElementInputMasksHooks::class)->webformElementInputMasksAlter($input_masks);
}
