_core:
  default_config_hash: zJS1GknUylh656CJSNXOupqKSqm6Xw200h1cq1eI970
enabled: true
timeout: 1800
max_timeout: 172800
padding: 60
no_individual_logout_threshold: false
role_logout: false
redirect_url: /user/login
no_dialog: true
message: 'Your session is about to expire. Do you want to reset it?'
inactivity_message: 'You have been logged out due to inactivity.'
inactivity_message_type: status
modal_width: 450
enforce_admin: true
jstimer_format: '%hours%:%mins%:%secs%'
jstimer_js_load_option: false
use_alt_logout_method: false
use_watchdog: false
dialog_title: 'Open Government - Government of Canada Alert'
whitelisted_ip_addresses: ''
