_core:
  default_config_hash: vdXLRPZRg35PBykBRRXr6RTql5EJR_fUi2kxyZ8c5m0
identity: drupal_open_canada_ca
facility: 128
format: '!base_url|!timestamp|!type|!severity|!ip|!request_uri|!referer|!uid|!link|!message'
