<?php

/**
 * @file
 * Support module for webform that provides handler invoke alter tests.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_test_handler_invoke_alter\Hook\WebformTestHandlerInvokeAlterHooks;
use Drupal\webform\Plugin\WebformHandlerInterface;

/**
 * Implements hook_webform_handler_invoke_alter().
 */
#[LegacyHook]
function webform_test_handler_invoke_alter_webform_handler_invoke_alter(WebformHandlerInterface $handler, $method_name, array $args) {
  \Drupal::service(WebformTestHandlerInvokeAlterHooks::class)->webformHandlerInvokeAlter($handler, $method_name, $args);
}

/**
 * Implements hook_webform_handler_invoke_METHOD_NAME_alter().
 */
function webform_test_handler_invoke_alter_webform_handler_invoke_pre_create_alter(WebformHandlerInterface $handler, array $args) {
  $t_args = [
    '@webform_id' => $handler->getWebform()->id(),
    '@handler_id' => $handler->getHandlerId(),
  ];
  \Drupal::messenger()->addStatus(t('Invoking hook_webform_handler_invoke_pre_create_alter() for "@webform_id:@handler_id"', $t_args), TRUE);
}
