<?php

/**
 * @file
 * Helps support Webform to Clientside Validation integration.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_clientside_validation\Hook\WebformClientsideValidationHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_submission_form_alter().
 */
#[LegacyHook]
function webform_clientside_validation_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(WebformClientsideValidationHooks::class)->webformSubmissionFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_element_info_alter().
 */
#[LegacyHook]
function webform_clientside_validation_element_info_alter(array &$info) {
  \Drupal::service(WebformClientsideValidationHooks::class)->elementInfoAlter($info);
}

/**
 * Process 'webform_email_confirm' element and add 'equal_to' validation rules.
 *
 * @see \Drupal\webform\Element\WebformEmailConfirm::processWebformEmailConfirm
 */
function _webform_clientside_validation_webform_email_confirm_process(&$element, FormStateInterface $form_state, &$complete_form) {
  $validation_properties = [
    '#equal_to' => $element['#name'] . '[mail_1]',
    '#equal_to_error' => t('The specified email addresses do not match.'),
  ];
  if (empty($element['#flexbox'])) {
    $element['mail_2'] += $validation_properties;
  }
  else {
    $element['flexbox']['mail_2'] += $validation_properties;
  }
  return $element;
}
