<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_type_breadcrumb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.content_type_breadcrumb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module will generate breadcrumbs for nodes of content type') . '</p>';
      return $output;

    default:
  }
}
