<?php

/**
 * @file
 * Provides an example that shows how to add custom properties to Webform elements.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_example_element_properties\Hook\WebformExampleElementPropertiesHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_default_properties_alter().
 */
#[LegacyHook]
function webform_example_element_properties_webform_element_default_properties_alter(array &$properties, array &$definition) {
  \Drupal::service(WebformExampleElementPropertiesHooks::class)->webformElementDefaultPropertiesAlter($properties, $definition);
}

/**
 * Implements hook_webform_element_translatable_properties_alter().
 */
#[LegacyHook]
function webform_example_element_properties_webform_element_translatable_properties_alter(array &$properties, array &$definition) {
  \Drupal::service(WebformExampleElementPropertiesHooks::class)->webformElementTranslatablePropertiesAlter($properties, $definition);
}

/**
 * Implements hook_webform_element_configuration_form_alter().
 */
#[LegacyHook]
function webform_example_element_properties_webform_element_configuration_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::service(WebformExampleElementPropertiesHooks::class)->webformElementConfigurationFormAlter($form, $form_state);
}

/**
 * Implements hook_webform_element_alter().
 */
#[LegacyHook]
function webform_example_element_properties_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  \Drupal::service(WebformExampleElementPropertiesHooks::class)->webformElementAlter($element, $form_state, $context);
}
