<?php

/**
 * @file
 * Test module for webform attachments.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_attachment_test\Hook\WebformAttachmentTestHooks;

/**
 * @file
 * Support module for webform attachment element that provides test webforms.
 */

/**
 * Implements hook_webform_load().
 */
#[LegacyHook]
function webform_attachment_test_webform_load(array $entities) {
  return \Drupal::service(WebformAttachmentTestHooks::class)->webformLoad($entities);
}
