<?php

/**
 * @file
 * Example module for custom handlers.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_example_handler\Hook\WebformExampleHandlerHooks;

/**
 * @file
 * Provides an example of a webform handler.
 */

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function webform_example_handler_theme() {
  return \Drupal::service(WebformExampleHandlerHooks::class)->theme();
}
