ckeditor.plugin.tokenbrowser:
  type: mapping
  label: 'Token browser'
  mapping:
    token_types:
      type: sequence
      label: 'Token types'
      sequence:
        type: string
        label: 'Token'
