<?php

/**
 * @file
 * Test module for webform cards.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_cards_test\Hook\WebformCardsTestHooks;

/**
 * @file
 * Support module for webform cards testing.
 */

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function webform_cards_test_theme() {
  return \Drupal::service(WebformCardsTestHooks::class)->theme();
}

/**
 * Prepares variables for webform 'wizard' progress templates.
 */
function template_preprocess_webform_progress__test_cards_progress_custom(array &$variables) {
  template_preprocess_webform_progress($variables);
  _template_preprocess_webform_progress($variables);
}
